### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml' 

### ISSUE THREAD

**Issue by k3mejia** [KaOSx/apps#121]
#### Submission type

  - [ ] Bug report

#### Package name & version you are having issues with or have a request for
qgis
> …

#### Used repositories
apps
> …

#### Expected behaviour
Qgis open
> …

#### Actual behaviour
qgis open but in the bigening a window inform:

Couldn't load plugin 'processing' 

ModuleNotFoundError: No module named 'yaml' 
Traceback (most recent call last):
  File "/usr/share/qgis/python/qgis/utils.py", line 312, in loadPlugin
    __import__(packageName)
  File "/usr/share/qgis/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/__init__.py", line 29, in 
    from processing.tools.general import *              # NOQA
  File "/usr/share/qgis/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 38, in 
    from processing.core.Processing import Processing
  File "/usr/share/qgis/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 45, in 
    from processing.script.ScriptUtils import ScriptUtils
  File "/usr/share/qgis/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/script/ScriptUtils.py", line 32, in 
    from processing.script.ScriptAlgorithm import ScriptAlgorithm
  File "/usr/share/qgis/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/script/ScriptAlgorithm.py", line 37, in 
    from processing.core.GeoAlgorithm import GeoAlgorithm
  File "/usr/share/qgis/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/core/GeoAlgorithm.py", line 49, in 
    from processing.algs.help import shortHelp
  File "/usr/share/qgis/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/usr/share/qgis/python/plugins/processing/algs/help/__init__.py", line 28, in 
    import yaml
  File "/usr/share/qgis/python/qgis/utils.py", line 647, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'yaml'

Versión de Python: 3.6.1 (default, Mar 22 2017, 21:57:16) [GCC 5.4.1 20170214] 
Versión de QGIS: 2.99.0-Master Master, exported 

Ruta de Python:
/usr/share/qgis/python
/home/kevin/.qgis3/python
/home/kevin/.qgis3/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/lib/python3.6/site-packages
/home/kevin/.qgis3//python
> …

#### Steps to reproduce the problem
Install and open the program
> …

#### System info link created by Octopi > Tools > SysInfo

> …

**Comment by demmm** [comment]
Seems PyYAML is a missing (new) depend, please test with newly added package:
```
sudo pacman -U http://kaosx.tk/repo/build/pyyaml-3.12-1-x86_64.pkg.tar.xz
```
if that fixes this for you too, qgis will be rebuild with this new depend.

**Comment by k3mejia** [comment]
Thanks,
I solved the problem but by downloading pyyaml from the official page.

**Comment by demmm** [comment]
pyyaml & rebuild qgis have moved to all users, closing.
