### ISSUE TITLE
ufw-frontends: ufw package not exists in python2

### ISSUE THREAD

**Issue by forostm** [KaOSx/apps#45]
ufw=0.35-1
ufw-frontends-0.3.2-1

ufw is installed in python3 but ufw-frontend is executed with python2.

```
[forostm@kaos ufw-frontends]$ sudo ufw-gtk                         
                                                                   
Traceback (most recent call last):                                                
  File "/usr/sbin/ufw-gtk", line 3, in <module>                                   
    from gfw.l10n import ufw_localize                                             
  File "/usr/lib/python2.7/site-packages/gfw/l10n.py", line 22, in <module>       
    import ufw.common                                                             
ImportError: No module named ufw.common 
```

**Comment by demmm** [comment]
Might be the end of ufw-frontend in the repos then, seems project is dead, this issue has been open a year:
https://github.com/baudm/ufw-frontends/issues/23

No commits other then porting to github since 2012

**Comment by demmm** [comment]
ufw-frontends is now removed from the repos
